# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4d6d35c55b6fd9070cb6cc9c72fc10577ac1414067230b9e3524718d017930faebe14d4dc698ecbbffd5a9e9f76b0584a43163c0ffd6737e28fd46e135ba7df0

test:
  secret_key_base: 408e198c73c4d579e4d8e494eb79016e104474f03cc0c7f6e5ea3573e770c61feb3793608a964436f99b2153c96e2abb6a417ebe3acf82bb72e97bce7b4b848b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
